### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by nextr71** [Spikeysanju/MotionToast#1]
Error is given when I sync my project
![Annotation 2020-03-16 050014](https://user-images.githubusercontent.com/62244602/76756836-ba0b6480-6743-11ea-9954-80ebc0771a9a.png)

**Comment by Spikeysanju** [comment]
> Could you please add this line in Project Level Gradle File

```
allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }

    }
}

```

**Comment by Spikeysanju** [comment]
This will solve the issue thanks!

**Comment by nextr71** [comment]
I have solved the issue thanks!
