### ISSUE TITLE
Toast not working in a service

### ISSUE THREAD

**Issue by Dhruvkanani** [Spikeysanju/MotionToast#10]
I am using your library in java language instead of kotlin. But I tried everything to use in the constructor of motion toast the first argument shows an error. I tried this, service_name.this, getapplicationcontext(). Then you said use service name.this.getapplicationcontext() but that also didn't worked. Solve this problem please. Thank You

**Comment by Spikeysanju** [comment]
Need more information about your service. If possible can you share your code?
