### ISSUE TITLE
Localized String for toast title

### ISSUE THREAD

**Issue by alisimsek98** [Spikeysanju/MotionToast#17]
As far as I understood, the title of the toast determined by the toast type, such as TOAST_ERROR, TOAST_WARNING etc.
Is there any way to custom assign the title text for language support except english.

**Comment by Spikeysanju** [comment]
Yesterday, I have released a custom toast where you can customize the colors only. But I'm planning to add custom title & message for a custom toast by today. Stay tuned!

**Comment by chetan882777** [comment]
Can I do a contribution adding localized strings for default title?
