### ISSUE TITLE
No class found after the latest update

### ISSUE THREAD

**Issue by NotNotMarshall** [Spikeysanju/MotionToast#22]
Hello, after I updated to 1.3.3.2 all the imports are broken and the Studio can't seem to find anything to import.
I think you haven't added them to any repo.
I did:
1. Clean
2. Rebuild
3. Invalidate Cache
4. Restart Studio
5. Restart PC

But did not work...

![image](https://user-images.githubusercontent.com/23288867/98099813-a452d700-1ead-11eb-8c4f-ccbcaaaef857.png)

![image](https://user-images.githubusercontent.com/23288867/98099876-bcc2f180-1ead-11eb-872e-fefea3c659dc.png)

I have already added         maven { url 'https://jitpack.io' }
to all repos in my root level build.gradle file but still not works...

verion 1.3.3.1 works fine.

**Comment by specializeddevel** [comment]
Hello, I have the same issue too

**Comment by Spikeysanju** [comment]
@specializeddevel @NotNotMarshall I'm working on it rn. It will be resolved by the EOD!

**Comment by Spikeysanju** [comment]
Issue resolved in latest PR 👍
