### ISSUE TITLE
Toast Duration

### ISSUE THREAD

**Issue by Kwenziwa** [Spikeysanju/MotionToast#25]
How to set custom Toast Duration, example 10 sec

**Comment by Spikeysanju** [comment]
Currently, `Motion Toast` doesn't have an option to add `custom timings`. I will mark this as a `feature request & work on it.` Thanks for using Motion Toast 🙌

**Comment by Amark18** [comment]
Hey @Spikeysanju, thanks for making Motion Toast. I was wondering if you were able to implement custom toast duration.

**Comment by ezechuka** [comment]
@Spikeysanju I would like to implement this feature.

**Comment by mariooooo** [comment]
hi @Spikeysanju, when this feature will be implemented?

**Comment by mariooooo** [comment]
@Spikeysanju 
I fixed it by adding `toast.show()` in `onTick` method, but this is work only for API<28
In android versions above principle of the toast has changed and so this fix will not work
[changed toast](https://stackoverflow.com/questions/51956971/illegalstateexception-of-toast-view-on-android-p-preview#:~:text=Apparently%2C%20toast%20messages,sometimes%20throw%20IllegalStateException.)

in google docs says:
> Starting from Android Build.VERSION_CODES#R, apps targeting API level Build.VERSION_CODES#R or higher that are in the background will not have custom toast views displayed.
[google docs](https://developer.android.com/reference/android/widget/Toast#:~:text=in%20the%20foreground.-,Starting%20from%20Android%20Build.VERSION_CODES%23R%2C%20apps%20targeting%20API%20level%20Build.VERSION_CODES%23R%20or%20higher%20that%20are%20in%20the%20background%20will%20not%20have%20custom%20toast%20views%20displayed.,-int)

```
private fun startTimer(duration: Long, toast: Toast) {
            val timer = object : CountDownTimer(duration, 1000) {
                override fun onTick(millisUntilFinished: Long) {
                     toast.show()
                }
                override fun onFinish() {
                     toast.cancel()
                }
            }
            timer.start()
        }
```
