### ISSUE TITLE
Toast method has private access

### ISSUE THREAD

**Issue by Akshshr** [Spikeysanju/MotionToast#5]
The image attached should be pretty self explanatory 

<img width="705" alt="Screenshot 2020-03-22 at 15 01 26" src="https://user-images.githubusercontent.com/11215286/77246514-1394f700-6c4e-11ea-884b-44e7261ac88d.png">

**Comment by Spikeysanju** [comment]
> This library is pure Kotlin based. For java, you can use code like below

```
     // Use Companion to get Toast Methods.

        MotionToast.Companion.createToast(this,"Upload Completed!",
                MotionToast.Companion.getTOAST_SUCCESS(),
                MotionToast.Companion.getGRAVITY_BOTTOM(),
                MotionToast.Companion.getSHORT_DURATION(),
                ResourcesCompat.getFont(this,R.font.helvetica_regular));


```
