### ISSUE TITLE
Fragment issue

### ISSUE THREAD

**Issue by Shivansh771** [Spikeysanju/MotionToast#60]
Motion toast runs fine on Activities, but on fragments the context should be passed as activity (If there's  a way to run it on a fragment do tell me ). Please fix it.

**Comment by DrewStephensCoding** [comment]
Have you tried requireActivity()

**Comment by Shivansh771** [comment]
> 

Yeah I was new to fragment back then and I didn't knew about requireactivity() back then  sorry for posting a issue that was not a ikssue
