### ISSUE TITLE
No works, why? 

### ISSUE THREAD

**Issue by mzfkr97** [Spikeysanju/MotionToast#7]
if (checkConnect()) {
            //toast(getString(R.string.no_internet_connection))
            MotionToast.createToast(this,"This is information toast!",
                MotionToast.TOAST_INFO,
                MotionToast.GRAVITY_BOTTOM,
                MotionToast.LONG_DURATION,
                ResourcesCompat.getFont(this,R.font.helvetica_regular))
        }

Sometimes opens many times in a row..... I dont undrstnd

**Comment by Spikeysanju** [comment]
>  I have tested it on my some of my production apps & it works perfectly fine. Could you please check your codebase once. I suggest you use latest version of this library.

![Screenshot_2020-04-25-15-25-25-895_www sanju motiontoast](https://user-images.githubusercontent.com/23400022/80276991-b0452b80-8709-11ea-9d8e-fdc385c0ec5d.jpg)
