### ISSUE TITLE
Unable to use toast in a service

### ISSUE THREAD

**Issue by Dhruvkanani** [Spikeysanju/MotionToast#9]
I am converting this kotlin toast into java and using it in activity. Here it works perfectly but when I tried to use it in a service the first argument of the MotionToast shows error as it doesn't accept 'this' as an argument. Hint is showed that it requires android.app.Activity as a first argument. It will be a pleasure to me and you if you solve this problem.

**Comment by Spikeysanju** [comment]
// Try this - Replace "this" with "YourServiceName.this.getApplicationContext()" - @Dhruvkanani 
`
        MotionToast.Companion.createToast( YourServiceName.this.getApplicationContext(),
                "Upload Completed!",
                MotionToast.Companion.getTOAST_SUCCESS(),
                MotionToast.Companion.getGRAVITY_BOTTOM(),
                MotionToast.Companion.getSHORT_DURATION(),
                ResourcesCompat.getFont(this,R.font.helvetica_regular));`

**Comment by Dhruvkanani** [comment]
Your idea didn't worked please give me a cocrete solution
